name: flutter_release
description: A tool for building and publishing Flutter apps.
version: 0.0.7
repository: https://github.com/Oberhauser-Dev/flutter_release

environment:
  sdk: '>=3.0.0 <4.0.0'

executables:
  flutter_release:

dependencies:
  args: ^2.4.2
  flutter_to_debian: ^2.0.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
