name: flutter_release
description: A tool for building, releasing, publishing and deploying Flutter apps.
version: 0.0.4
repository: https://github.com/Oberhauser-Dev/flutter_release

environment:
  sdk: '>=2.18.0 <4.0.0'

executables:
  flutter_release:

dependencies:
  args: ^2.4.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
