name: flutter_release
description: A tool for building, releasing and deploying Flutter apps.
version: 0.0.1
repository: https://github.com/Oberhauser-Dev/flutter_release

environment:
  sdk: ^3.0.2

dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
