name: material_duration_picker
description: "A duration picker using the material design of the time picker."
version: 0.0.1
repository: https://github.com/Oberhauser-Dev/dart_packages/tree/main/packages/material_duration_picker

environment:
  sdk: ^3.5.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
