name: Publish packages
on:
  workflow_dispatch:

jobs:
  publish-packages:
    name: Publish packages
    permissions:
      contents: write
      id-token: write # Required for authentication using OIDC
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
      - uses: Gustl22/melos-action@publish
        with:
          publish: true
          git-email: info@oberhauser.dev
          git-name: Oberhauser Dev
